'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace WsRNP
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WsRNP.MIPISoap")>  _
    Public Interface MIPISoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadInfantesPaisEdad", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadInfantesPaisEdad(ByVal edad As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadInfantesPaisEdad", ReplyAction:="*")>  _
        Function CantidadInfantesPaisEdadAsync(ByVal edad As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadInfantesDepartamentoEdad", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadInfantesDepartamentoEdad(ByVal IdDepartamento As Integer, ByVal edad As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadInfantesDepartamentoEdad", ReplyAction:="*")>  _
        Function CantidadInfantesDepartamentoEdadAsync(ByVal IdDepartamento As Integer, ByVal edad As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadInfantesMunicipioEdad", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadInfantesMunicipioEdad(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal edad As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadInfantesMunicipioEdad", ReplyAction:="*")>  _
        Function CantidadInfantesMunicipioEdadAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal edad As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadInfantesZonaEdad", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadInfantesZonaEdad(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer, ByVal edad As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadInfantesZonaEdad", ReplyAction:="*")>  _
        Function CantidadInfantesZonaEdadAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer, ByVal edad As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/consultaNominal", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function consultaNominal(ByVal NumeroIdentidad As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/consultaNominal", ReplyAction:="*")>  _
        Function consultaNominalAsync(ByVal NumeroIdentidad As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface MIPISoapChannel
        Inherits WsRNP.MIPISoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MIPISoapClient
        Inherits System.ServiceModel.ClientBase(Of WsRNP.MIPISoap)
        Implements WsRNP.MIPISoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CantidadInfantesPaisEdad(ByVal edad As Integer) As Double Implements WsRNP.MIPISoap.CantidadInfantesPaisEdad
            Return MyBase.Channel.CantidadInfantesPaisEdad(edad)
        End Function
        
        Public Function CantidadInfantesPaisEdadAsync(ByVal edad As Integer) As System.Threading.Tasks.Task(Of Double) Implements WsRNP.MIPISoap.CantidadInfantesPaisEdadAsync
            Return MyBase.Channel.CantidadInfantesPaisEdadAsync(edad)
        End Function
        
        Public Function CantidadInfantesDepartamentoEdad(ByVal IdDepartamento As Integer, ByVal edad As Integer) As Double Implements WsRNP.MIPISoap.CantidadInfantesDepartamentoEdad
            Return MyBase.Channel.CantidadInfantesDepartamentoEdad(IdDepartamento, edad)
        End Function
        
        Public Function CantidadInfantesDepartamentoEdadAsync(ByVal IdDepartamento As Integer, ByVal edad As Integer) As System.Threading.Tasks.Task(Of Double) Implements WsRNP.MIPISoap.CantidadInfantesDepartamentoEdadAsync
            Return MyBase.Channel.CantidadInfantesDepartamentoEdadAsync(IdDepartamento, edad)
        End Function
        
        Public Function CantidadInfantesMunicipioEdad(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal edad As Integer) As Double Implements WsRNP.MIPISoap.CantidadInfantesMunicipioEdad
            Return MyBase.Channel.CantidadInfantesMunicipioEdad(IdDepartamento, IdMunicipio, edad)
        End Function
        
        Public Function CantidadInfantesMunicipioEdadAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal edad As Integer) As System.Threading.Tasks.Task(Of Double) Implements WsRNP.MIPISoap.CantidadInfantesMunicipioEdadAsync
            Return MyBase.Channel.CantidadInfantesMunicipioEdadAsync(IdDepartamento, IdMunicipio, edad)
        End Function
        
        Public Function CantidadInfantesZonaEdad(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer, ByVal edad As Integer) As Double Implements WsRNP.MIPISoap.CantidadInfantesZonaEdad
            Return MyBase.Channel.CantidadInfantesZonaEdad(IdDepartamento, IdMunicipio, IdZona, edad)
        End Function
        
        Public Function CantidadInfantesZonaEdadAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer, ByVal edad As Integer) As System.Threading.Tasks.Task(Of Double) Implements WsRNP.MIPISoap.CantidadInfantesZonaEdadAsync
            Return MyBase.Channel.CantidadInfantesZonaEdadAsync(IdDepartamento, IdMunicipio, IdZona, edad)
        End Function
        
        Public Function consultaNominal(ByVal NumeroIdentidad As String) As System.Data.DataSet Implements WsRNP.MIPISoap.consultaNominal
            Return MyBase.Channel.consultaNominal(NumeroIdentidad)
        End Function
        
        Public Function consultaNominalAsync(ByVal NumeroIdentidad As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements WsRNP.MIPISoap.consultaNominalAsync
            Return MyBase.Channel.consultaNominalAsync(NumeroIdentidad)
        End Function
    End Class
End Namespace
