'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference3
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference3.rnpSoap")>  _
    Public Interface rnpSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListMatriculaPreBasicaDepartamento", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListMatriculaPreBasicaDepartamento() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListMatriculaPreBasicaDepartamento", ReplyAction:="*")>  _
        Function ListMatriculaPreBasicaDepartamentoAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListMatriculaPreBasicaMunicipio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ListMatriculaPreBasicaMunicipio() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ListMatriculaPreBasicaMunicipio", ReplyAction:="*")>  _
        Function ListMatriculaPreBasicaMunicipioAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface rnpSoapChannel
        Inherits ServiceReference3.rnpSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class rnpSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference3.rnpSoap)
        Implements ServiceReference3.rnpSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ListMatriculaPreBasicaDepartamento() As System.Data.DataSet Implements ServiceReference3.rnpSoap.ListMatriculaPreBasicaDepartamento
            Return MyBase.Channel.ListMatriculaPreBasicaDepartamento
        End Function
        
        Public Function ListMatriculaPreBasicaDepartamentoAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference3.rnpSoap.ListMatriculaPreBasicaDepartamentoAsync
            Return MyBase.Channel.ListMatriculaPreBasicaDepartamentoAsync
        End Function
        
        Public Function ListMatriculaPreBasicaMunicipio() As System.Data.DataSet Implements ServiceReference3.rnpSoap.ListMatriculaPreBasicaMunicipio
            Return MyBase.Channel.ListMatriculaPreBasicaMunicipio
        End Function
        
        Public Function ListMatriculaPreBasicaMunicipioAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference3.rnpSoap.ListMatriculaPreBasicaMunicipioAsync
            Return MyBase.Channel.ListMatriculaPreBasicaMunicipioAsync
        End Function
    End Class
End Namespace
