'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace WsSace
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WsSace.SIM_SACESoap")>  _
    Public Interface SIM_SACESoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadEstimulacionTempranaPais", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadEstimulacionTempranaPais() As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadEstimulacionTempranaPais", ReplyAction:="*")>  _
        Function CantidadEstimulacionTempranaPaisAsync() As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadEstimulacionTempranaDepartamento", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadEstimulacionTempranaDepartamento(ByVal IdDepartamento As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadEstimulacionTempranaDepartamento", ReplyAction:="*")>  _
        Function CantidadEstimulacionTempranaDepartamentoAsync(ByVal IdDepartamento As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadEstimulacionTempranaMunicipio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadEstimulacionTempranaMunicipio(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadEstimulacionTempranaMunicipio", ReplyAction:="*")>  _
        Function CantidadEstimulacionTempranaMunicipioAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadEstimulacionTempranaZona", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadEstimulacionTempranaZona(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadEstimulacionTempranaZona", ReplyAction:="*")>  _
        Function CantidadEstimulacionTempranaZonaAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ConsultaEstimulacionTempranaNominal", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ConsultaEstimulacionTempranaNominal(ByVal NumeroIdentidad As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ConsultaEstimulacionTempranaNominal", ReplyAction:="*")>  _
        Function ConsultaEstimulacionTempranaNominalAsync(ByVal NumeroIdentidad As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadAlimentacionEscolarPais", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadAlimentacionEscolarPais() As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadAlimentacionEscolarPais", ReplyAction:="*")>  _
        Function CantidadAlimentacionEscolarPaisAsync() As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadAlimentacionEscolarDepartamento", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadAlimentacionEscolarDepartamento(ByVal IdDepartamento As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadAlimentacionEscolarDepartamento", ReplyAction:="*")>  _
        Function CantidadAlimentacionEscolarDepartamentoAsync(ByVal IdDepartamento As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadAlimentacionEscolarMunicipio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadAlimentacionEscolarMunicipio(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadAlimentacionEscolarMunicipio", ReplyAction:="*")>  _
        Function CantidadAlimentacionEscolarMunicipioAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadAlimentacionEscolarZona", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadAlimentacionEscolarZona(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadAlimentacionEscolarZona", ReplyAction:="*")>  _
        Function CantidadAlimentacionEscolarZonaAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ConsultaAlimentacionEscolarNominal", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ConsultaAlimentacionEscolarNominal(ByVal NumeroIdentidad As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ConsultaAlimentacionEscolarNominal", ReplyAction:="*")>  _
        Function ConsultaAlimentacionEscolarNominalAsync(ByVal NumeroIdentidad As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadPrebasicaPaisEdad", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadPrebasicaPaisEdad(ByVal edad As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadPrebasicaPaisEdad", ReplyAction:="*")>  _
        Function CantidadPrebasicaPaisEdadAsync(ByVal edad As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadPrebasicaDepartamento", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadPrebasicaDepartamento(ByVal IdDepartamento As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadPrebasicaDepartamento", ReplyAction:="*")>  _
        Function CantidadPrebasicaDepartamentoAsync(ByVal IdDepartamento As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadPrebasicaMunicipio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadPrebasicaMunicipio(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadPrebasicaMunicipio", ReplyAction:="*")>  _
        Function CantidadPrebasicaMunicipioAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadPrebasicaZona", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadPrebasicaZona(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadPrebasicaZona", ReplyAction:="*")>  _
        Function CantidadPrebasicaZonaAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadPrebasicaNominal", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CantidadPrebasicaNominal(ByVal NumeroIdentidad As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CantidadPrebasicaNominal", ReplyAction:="*")>  _
        Function CantidadPrebasicaNominalAsync(ByVal NumeroIdentidad As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SIM_SACESoapChannel
        Inherits WsSace.SIM_SACESoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SIM_SACESoapClient
        Inherits System.ServiceModel.ClientBase(Of WsSace.SIM_SACESoap)
        Implements WsSace.SIM_SACESoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CantidadEstimulacionTempranaPais() As Double Implements WsSace.SIM_SACESoap.CantidadEstimulacionTempranaPais
            Return MyBase.Channel.CantidadEstimulacionTempranaPais
        End Function
        
        Public Function CantidadEstimulacionTempranaPaisAsync() As System.Threading.Tasks.Task(Of Double) Implements WsSace.SIM_SACESoap.CantidadEstimulacionTempranaPaisAsync
            Return MyBase.Channel.CantidadEstimulacionTempranaPaisAsync
        End Function
        
        Public Function CantidadEstimulacionTempranaDepartamento(ByVal IdDepartamento As Integer) As Double Implements WsSace.SIM_SACESoap.CantidadEstimulacionTempranaDepartamento
            Return MyBase.Channel.CantidadEstimulacionTempranaDepartamento(IdDepartamento)
        End Function
        
        Public Function CantidadEstimulacionTempranaDepartamentoAsync(ByVal IdDepartamento As Integer) As System.Threading.Tasks.Task(Of Double) Implements WsSace.SIM_SACESoap.CantidadEstimulacionTempranaDepartamentoAsync
            Return MyBase.Channel.CantidadEstimulacionTempranaDepartamentoAsync(IdDepartamento)
        End Function
        
        Public Function CantidadEstimulacionTempranaMunicipio(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer) As Double Implements WsSace.SIM_SACESoap.CantidadEstimulacionTempranaMunicipio
            Return MyBase.Channel.CantidadEstimulacionTempranaMunicipio(IdDepartamento, IdMunicipio)
        End Function
        
        Public Function CantidadEstimulacionTempranaMunicipioAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer) As System.Threading.Tasks.Task(Of Double) Implements WsSace.SIM_SACESoap.CantidadEstimulacionTempranaMunicipioAsync
            Return MyBase.Channel.CantidadEstimulacionTempranaMunicipioAsync(IdDepartamento, IdMunicipio)
        End Function
        
        Public Function CantidadEstimulacionTempranaZona(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer) As Double Implements WsSace.SIM_SACESoap.CantidadEstimulacionTempranaZona
            Return MyBase.Channel.CantidadEstimulacionTempranaZona(IdDepartamento, IdMunicipio, IdZona)
        End Function
        
        Public Function CantidadEstimulacionTempranaZonaAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer) As System.Threading.Tasks.Task(Of Double) Implements WsSace.SIM_SACESoap.CantidadEstimulacionTempranaZonaAsync
            Return MyBase.Channel.CantidadEstimulacionTempranaZonaAsync(IdDepartamento, IdMunicipio, IdZona)
        End Function
        
        Public Function ConsultaEstimulacionTempranaNominal(ByVal NumeroIdentidad As String) As System.Data.DataSet Implements WsSace.SIM_SACESoap.ConsultaEstimulacionTempranaNominal
            Return MyBase.Channel.ConsultaEstimulacionTempranaNominal(NumeroIdentidad)
        End Function
        
        Public Function ConsultaEstimulacionTempranaNominalAsync(ByVal NumeroIdentidad As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements WsSace.SIM_SACESoap.ConsultaEstimulacionTempranaNominalAsync
            Return MyBase.Channel.ConsultaEstimulacionTempranaNominalAsync(NumeroIdentidad)
        End Function
        
        Public Function CantidadAlimentacionEscolarPais() As Double Implements WsSace.SIM_SACESoap.CantidadAlimentacionEscolarPais
            Return MyBase.Channel.CantidadAlimentacionEscolarPais
        End Function
        
        Public Function CantidadAlimentacionEscolarPaisAsync() As System.Threading.Tasks.Task(Of Double) Implements WsSace.SIM_SACESoap.CantidadAlimentacionEscolarPaisAsync
            Return MyBase.Channel.CantidadAlimentacionEscolarPaisAsync
        End Function
        
        Public Function CantidadAlimentacionEscolarDepartamento(ByVal IdDepartamento As Integer) As Double Implements WsSace.SIM_SACESoap.CantidadAlimentacionEscolarDepartamento
            Return MyBase.Channel.CantidadAlimentacionEscolarDepartamento(IdDepartamento)
        End Function
        
        Public Function CantidadAlimentacionEscolarDepartamentoAsync(ByVal IdDepartamento As Integer) As System.Threading.Tasks.Task(Of Double) Implements WsSace.SIM_SACESoap.CantidadAlimentacionEscolarDepartamentoAsync
            Return MyBase.Channel.CantidadAlimentacionEscolarDepartamentoAsync(IdDepartamento)
        End Function
        
        Public Function CantidadAlimentacionEscolarMunicipio(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer) As Double Implements WsSace.SIM_SACESoap.CantidadAlimentacionEscolarMunicipio
            Return MyBase.Channel.CantidadAlimentacionEscolarMunicipio(IdDepartamento, IdMunicipio)
        End Function
        
        Public Function CantidadAlimentacionEscolarMunicipioAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer) As System.Threading.Tasks.Task(Of Double) Implements WsSace.SIM_SACESoap.CantidadAlimentacionEscolarMunicipioAsync
            Return MyBase.Channel.CantidadAlimentacionEscolarMunicipioAsync(IdDepartamento, IdMunicipio)
        End Function
        
        Public Function CantidadAlimentacionEscolarZona(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer) As Double Implements WsSace.SIM_SACESoap.CantidadAlimentacionEscolarZona
            Return MyBase.Channel.CantidadAlimentacionEscolarZona(IdDepartamento, IdMunicipio, IdZona)
        End Function
        
        Public Function CantidadAlimentacionEscolarZonaAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer) As System.Threading.Tasks.Task(Of Double) Implements WsSace.SIM_SACESoap.CantidadAlimentacionEscolarZonaAsync
            Return MyBase.Channel.CantidadAlimentacionEscolarZonaAsync(IdDepartamento, IdMunicipio, IdZona)
        End Function
        
        Public Function ConsultaAlimentacionEscolarNominal(ByVal NumeroIdentidad As String) As System.Data.DataSet Implements WsSace.SIM_SACESoap.ConsultaAlimentacionEscolarNominal
            Return MyBase.Channel.ConsultaAlimentacionEscolarNominal(NumeroIdentidad)
        End Function
        
        Public Function ConsultaAlimentacionEscolarNominalAsync(ByVal NumeroIdentidad As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements WsSace.SIM_SACESoap.ConsultaAlimentacionEscolarNominalAsync
            Return MyBase.Channel.ConsultaAlimentacionEscolarNominalAsync(NumeroIdentidad)
        End Function
        
        Public Function CantidadPrebasicaPaisEdad(ByVal edad As Integer) As Double Implements WsSace.SIM_SACESoap.CantidadPrebasicaPaisEdad
            Return MyBase.Channel.CantidadPrebasicaPaisEdad(edad)
        End Function
        
        Public Function CantidadPrebasicaPaisEdadAsync(ByVal edad As Integer) As System.Threading.Tasks.Task(Of Double) Implements WsSace.SIM_SACESoap.CantidadPrebasicaPaisEdadAsync
            Return MyBase.Channel.CantidadPrebasicaPaisEdadAsync(edad)
        End Function
        
        Public Function CantidadPrebasicaDepartamento(ByVal IdDepartamento As Integer) As Double Implements WsSace.SIM_SACESoap.CantidadPrebasicaDepartamento
            Return MyBase.Channel.CantidadPrebasicaDepartamento(IdDepartamento)
        End Function
        
        Public Function CantidadPrebasicaDepartamentoAsync(ByVal IdDepartamento As Integer) As System.Threading.Tasks.Task(Of Double) Implements WsSace.SIM_SACESoap.CantidadPrebasicaDepartamentoAsync
            Return MyBase.Channel.CantidadPrebasicaDepartamentoAsync(IdDepartamento)
        End Function
        
        Public Function CantidadPrebasicaMunicipio(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer) As Double Implements WsSace.SIM_SACESoap.CantidadPrebasicaMunicipio
            Return MyBase.Channel.CantidadPrebasicaMunicipio(IdDepartamento, IdMunicipio)
        End Function
        
        Public Function CantidadPrebasicaMunicipioAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer) As System.Threading.Tasks.Task(Of Double) Implements WsSace.SIM_SACESoap.CantidadPrebasicaMunicipioAsync
            Return MyBase.Channel.CantidadPrebasicaMunicipioAsync(IdDepartamento, IdMunicipio)
        End Function
        
        Public Function CantidadPrebasicaZona(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer) As Double Implements WsSace.SIM_SACESoap.CantidadPrebasicaZona
            Return MyBase.Channel.CantidadPrebasicaZona(IdDepartamento, IdMunicipio, IdZona)
        End Function
        
        Public Function CantidadPrebasicaZonaAsync(ByVal IdDepartamento As Integer, ByVal IdMunicipio As Integer, ByVal IdZona As Integer) As System.Threading.Tasks.Task(Of Double) Implements WsSace.SIM_SACESoap.CantidadPrebasicaZonaAsync
            Return MyBase.Channel.CantidadPrebasicaZonaAsync(IdDepartamento, IdMunicipio, IdZona)
        End Function
        
        Public Function CantidadPrebasicaNominal(ByVal NumeroIdentidad As String) As System.Data.DataSet Implements WsSace.SIM_SACESoap.CantidadPrebasicaNominal
            Return MyBase.Channel.CantidadPrebasicaNominal(NumeroIdentidad)
        End Function
        
        Public Function CantidadPrebasicaNominalAsync(ByVal NumeroIdentidad As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements WsSace.SIM_SACESoap.CantidadPrebasicaNominalAsync
            Return MyBase.Channel.CantidadPrebasicaNominalAsync(NumeroIdentidad)
        End Function
    End Class
End Namespace
